language: java

jdk:
 - oraclejdk8

env:
- TERM=dumb

script: ./mvnw package

after_success:
  - mvn clean test jacoco:report coveralls:report

cache:
  directories:
  - ~/.m2/repository
  - ~/.m2/wrapper


